lib/FusionInventory/Agent/HTTP/Client/Fusion.pm
lib/FusionInventory/Agent/Task/Collect.pm
t/tasks/collect.t
t/tasks/collect/findfile.t

This is my first attempt to fix and enhance the collect task in agent for 2.3.x branch.
It includes a FusionInventory::Agent::HTTP::Client::Fusion modification to automatically use POST method in the case remote fusioninventory-for-glpi plugin supports it (a separate pull request for 0.84 plugin branch will be available). This enhancement is also CRSF compliant as requested for the GLPI plugin.
I added unit tests. findFile collect function case unit tests are not complete and I need to add unit tests dedicated to getFromRegistry and getFromWMI functions.

2.3.x+task collect

---

bin/fusioninventory-netinventory
etc/agent.cfg
etc/agent.cfg.pod
lib/FusionInventory/Agent/Config.pm
lib/FusionInventory/Agent/Task.pm
lib/FusionInventory/Agent/Task/NetInventory.pm
lib/FusionInventory/Agent/Tools/Hardware.pm

These commits add the possibility to consider aggregation ports as trunk ports to fix some association issues with non-cisco switches.

Add the possibility to consider aggregation ports as trunk ports

---

bin/fusioninventory-netinventory
etc/agent.cfg
etc/agent.cfg.pod
lib/FusionInventory/Agent/Config.pm
lib/FusionInventory/Agent/Task.pm
lib/FusionInventory/Agent/Task/NetInventory.pm
lib/FusionInventory/Agent/Tools/Hardware.pm

For few users, trunk port detection won't work due to a coding shortcut taken in the _getTrunkPorts sub.
This pull request fixes the problem by adding a new option (trunk_pvid) which will be used to manually select the PVID, for better trunk port detection when using the "lldpXdot1LocPortVlanId" method, without changing anything for users who doesn't have the problem, as the default value remains 0.

[Bugfix] Allow the user to select the trunk PVID

---

lib/FusionInventory/Agent/Task/Inventory/Generic/Rudder.pm

use English module in Rudder to avoid failing require() while loaded from fusioninventory-agent apps

Add English module use as this fix unittest failing on Rudder module require() try

---

lib/FusionInventory/Agent/Task/Inventory/Linux/Networks/FibreChannel.pm
lib/FusionInventory/Agent/Task/Inventory/Solaris/Networks.pm
lib/FusionInventory/Agent/Tools.pm
resources/solaris/fcinfo_hba-port/sample-2
t/tasks/inventory/linux/networks/fibrechannel.t
t/tasks/inventory/solaris/networks.t

We should normalize the reported network interface speed value when it can be as Mbits/s like specified here:
http://www.fusioninventory.org/documentation/dev/spec/protocol/inventory/
...
<!ELEMENT SPEED (#PCDATA)>
...

2.3.x+normalize reported network speed

---

lib/FusionInventory/Agent/Task/Inventory/Virtualization/Vmsystem.pm

This PR extends PR #53 as I don't see why we are doing a check against ->{h}{CONTENT} where this hash value should not be available.

2.3.x+check fix

---

lib/FusionInventory/Agent/Config.pm

Hello,
When split is used on other value than scalar like array ref or hash ref, it gives results... but these results are not expected. 
With this fix, removing duplicate keys can be done.
Regards.

2.3.x bug do split only on scalar

---

bin/fusioninventory-agent
etc/agent.cfg
lib/FusionInventory/Agent.pm
lib/FusionInventory/Agent/Config.pm
lib/FusionInventory/Agent/Tools.pm
resources/config/sample4
t/agent/agent.t
t/agent/config.t

New feature : tasks execution plan.
Parameter 'tasks' can be filled for example like this : task1,task2,task3
Only these tasks will be executed. If there is at the end of the list the word '...', all available tasks not executed yet will be executed.
Examples :
--tasks=task1,task2,task1 Executes task1, task2, task1 and then stops.
--tasks=task1,task2,task1,... Executes task1, task2, task1 and then all other available tasks.

New feature : tasks execution plan

---

Makefile.PL
bin/fusioninventory-agent
etc/agent.cfg
lib/FusionInventory/Agent.pm
lib/FusionInventory/Agent/Config.pm
t/agent/agent.t
t/agent/config.t
t/lib/FusionInventory/Test/Utils.pm

The agent's configuration can be reloaded from backend every N seconds where N is the value passed in the option 'conf-reload-interval'.
The default value for this option is '0', which means that the configuration is never reloaded.

New feature : Configuration reload

---

lib/FusionInventory/Agent.pm
t/agent/agent.t

Fix
When merging 2.3.x branch with conf reload feature branch, the computation of tasks execution plan were not copied in new reinit() method. So the tasks execution plan was lost after conf reloading...
Now fixed.

2.3.x bug tasks execution plan lost when config reload

---

lib/FusionInventory/Agent/Task/Inventory/Win32/AntiVirus.pm

1) sprintf does not convert anything, it simply prints... so use of hex function is required 
There as a failure when converting version numbers. They are hex values so they have to be converted with hex function and then printed as integers with sprintf
We have hex values like '0x000016a8' and we want to convert it to integers
2) use of @_ instead of shift to get the function parameters...

bug : McAfee antivirus data on Win32

---

etc/agent.cfg
lib/FusionInventory/Agent.pm

1) Due to case insensitive option ('tasks' option), the real case of task names was lost
2) For the tasks option, when using the example provided in file 'etc/agent.cfg' (just uncommenting the line), the option did not work : the values must be written separated by a comma and no space character.

Bug : after config reload, wrong display of planned tasks

---

bin/fusioninventory-agent
lib/FusionInventory/Agent/Config.pm
resources/config/sample2
resources/config/sample3
resources/config/sample4
t/agent/config.t

As suggested, we introduce a minimum for 'conf-reload-interval' option. For now, this minimum is set to 60 (in seconds)

Forced minimum for 'conf-reload-interval' option

---

Makefile.PL
bin/fusioninventory-agent
bin/fusioninventory-win32-service
lib/FusionInventory/Agent/Tools/Win32.pm
t/01compile.t
t/agent/tools/win32.t
t/tasks/deploy/p2p.t
t/tasks/inventory/virtualization/hyperv.t
t/tasks/inventory/windows/bios.t
t/tasks/inventory/windows/cpu.t
t/tasks/inventory/windows/drives.t
t/tasks/inventory/windows/license.t
t/tasks/inventory/windows/memory.t
t/tasks/inventory/windows/networks.t
t/tasks/inventory/windows/printers.t
t/tasks/inventory/windows/registry.t
t/tasks/inventory/windows/softwares.t
t/tasks/inventory/windows/storages.t
t/tasks/inventory/windows/usb.t
t/tasks/wakeonlan.t

Use Perl threads to handle a dedicated worker thread. This thread only job is just to handle few calls from FusionInventory::Agent::Tools::Win32 that are known to crash perl under win32. This calls are using Win32:OLE module and and as this last depends on not thread-safe system DLL, they can trigger crash while forked tasks are exiting.

2.3.x+use perl threading to avoid crash under win32

---

Makefile.PL
lib/FusionInventory/Agent/Config.pm

Module 'Data::Structure::Util' is not used any more. So, some cleaning is welcome.

useless module cleaning

---

lib/FusionInventory/Agent/Task/Inventory/Solaris/Softwares.pm
resources/solaris/pkg-info/sample
resources/solaris/pkg-info/sample-sol10
t/tasks/inventory/solaris/softwares.t

Solaris 11 and later use "pkg".
The earlier "pkginfo" is still present in Solaris 11, but does not provide all the information "pkg" does, like e.g. the overall patch level of the OS.

recognize Solaris 11 and later and use its own packaging tool

---

lib/FusionInventory/Agent/SOAP/VMware.pm

Fix `500 Can't connect to X.X.X.X:443 (certificate verify failed)` error messages on ESX task requests.

Do not verify SSL mode while connecting to VMware server

---

bin/fusioninventory-win32-service

Parameters in command line must be quoted... if not,, the service's startup  will silently crash if one of the parameters contains a space character (Documents ans settings  windows folder for instance)

2.3.x Win32 : Bug when starting agent from sources

---

lib/FusionInventory/Agent/Task/Inventory/MacOS.pm

boottime not retrieved on Mac Os 10.4. Now fixed

2.3.x bug mac os104 boottime

---

lib/FusionInventory/Agent/Task/Inventory/Virtualization/HyperV.pm
lib/FusionInventory/Agent/Tools/Win32.pm

* Add support for alternate moniker in getWMIObjects() API
* Try to use alternate moniker as fallback if new Hyper-V WMI namespace is not found
This should fix [forge bug 2872](http://forge.fusioninventory.org/issues/2872)
[Tests passed on Appveyor](https://ci.appveyor.com/project/g-bougard/fusioninventory-agent/build/2.3.x+hyperV-fix-119)

2.3.x+hyper v fix

---

lib/FusionInventory/Agent/Task/Inventory/MacOS.pm
lib/FusionInventory/Agent/Task/Inventory/MacOS/Uptime.pm
lib/FusionInventory/Agent/Tools/MacOS.pm
t/agent/tools/macos.t
t/tasks/inventory/macos/uptime.t

MacOS/Uptime.pm function named '_getBootTime' has been deleted. Its content have been moved in Tools/MacOS.pm. This code has been completed to have a default value for 'command' parameter.
Add of unit test for this new function in Tools/MacOS.pm

Mac OS X boottime refactoring

---

lib/FusionInventory/Agent/Tools.pm

An example. 
Regex /(?: sec = (\d+)|(\d+)$)/ can return a list with an undef value. The getFirstMatch() function takes the first, even it's undef... gives unexpected result.
I propose, in scalar context, to return first defined value in list.

In scalar context, Tools::GetFirstMatch() can return undef

---

Makefile.PL
lib/FusionInventory/Agent/Tools/MacOS.pm
t/agent/tools/macos.t

Module Tie::IxHash is required only on Mac OS X now. Inventory tools' function and unit tests run only if module can be imported at runtime.

Excessive use directive (module needed only on Mac OS X)

---

lib/FusionInventory/Agent/Task/Inventory/Win32/Users.pm
lib/FusionInventory/Agent/Tools/Win32.pm

This update is important for service mode as we want to load Win32::OLE in only one dedicated thread

Don't use Win32::OLE module in Users inventory

---

lib/FusionInventory/Agent.pm
lib/FusionInventory/Agent/Tools.pm
lib/FusionInventory/Agent/Tools/Generic.pm
lib/FusionInventory/Agent/Tools/Win32.pm

This PR concerns mostly Win32 platform. For other platforms, only the IDS databases preload is relevant.
The most important is an attempt to limit the memory usage under win32.

2.3.x+service optimizations

---

lib/FusionInventory/Agent/Task/Inventory/MacOS/Hostname.pm

The ComputerName entry is available in SPSoftwareDataType only, SPApplicationsDataType does't have this entry which was leading to return an empty value.

OSX: Fix Hostname.pm for getting the ComputerName 

---

lib/FusionInventory/Agent/Inventory.pm
lib/FusionInventory/Agent/Task/Inventory/Linux.pm
lib/FusionInventory/Agent/Task/Inventory/Solaris.pm

hostid command output is sometime required for proprietary software licensing

Support HOSTID on OPERATINGSYSTEM node for linux & solaris inventory

---

lib/FusionInventory/Agent/Task/Inventory/Generic/Remote_Mgmt/TeamViewer.pm

TeamViewer test is failing on Win32. 
It's when TeamViewer has been uninstalled. The key TeamViewer is still present in registry but empty. 
Our test to see if module is enabled was not sufficient so I had a check to see if the key contains subkeys.

must check if key contains subkeys

---

lib/FusionInventory/Agent.pm
lib/FusionInventory/Agent/HTTP/Server.pm
lib/FusionInventory/Agent/Target.pm

Avoid an issue where target can be retried too early on network/server error.
The issue can be triggered while inventory is forced through agent http interface.

Target API refactoring to avoid minor issue

---

lib/FusionInventory/Agent/Inventory.pm

Fix crash case, wrong API call and wrong checksum-ing
Also initialize logger while not instanciated from the agent

2.3.x+fix crash on corrupted state file

---

Makefile.PL
circle.yml
lib/FusionInventory/Agent/Task/Inventory/MacOS/Softwares.pm
lib/FusionInventory/Agent/Tools/MacOS.pm
t/agent/tools/macos.t

Mac Os X software retrieving refactoring, now using XML::XPath to parse system_profiler XML output, and as a consequence, cleaning a few functions

Mac Os X refacto using XML::XPath

---

lib/FusionInventory/Agent/Task/WakeOnLan.pm

PR for #294 
From work for my local situation (fusion agent from std repo on ubuntu 14.04). Untested else where.
Agent debug log before : 
> [Tue May 16 18:07:15 2017][debug] running task WakeOnLan in process 15699
> [Tue May 16 18:07:15 2017][debug] FusionInventory WakeOnLan task 2.0
> [Tue May 16 18:07:15 2017][debug] Sending magic packet to 14xxxxxxxx85 as ethernet frame
Agent debug log after :
> [Wed May 17 14:27:20 2017][debug] running task WakeOnLan in process 10912
> [Wed May 17 14:27:20 2017][debug] FusionInventory WakeOnLan task 2.0
> [Wed May 17 14:27:20 2017][debug] Sending magic packet to 14xxxxxxxx85 as ethernet frame on eth0
> [Wed May 17 14:27:20 2017][debug] Sending magic packet to 14xxxxxxxx85 as ethernet frame on eth1
> [Wed May 17 14:27:20 2017][debug] Sending magic …

2.3.x+wakeonlan send to all non-loopback non-dumb interfaces

---

lib/FusionInventory/Agent/Inventory.pm
lib/FusionInventory/Agent/Task/Inventory/Linux/i386/CPU.pm
lib/FusionInventory/Agent/Task/Inventory/Win32/CPU.pm
lib/FusionInventory/Agent/Tools/Generic.pm
resources/generic/dmidecode/oracle-server-6.7-oda
resources/generic/dmidecode/rhel-6.2-vmware-2vcpus
resources/linux/proc/cpuinfo/oracle-server-6.7-oda
resources/linux/proc/cpuinfo/rhel-6.2-vmware-2vcpus
t/agent/tools/generic.t
t/tasks/inventory/linux/cpu.t
t/tasks/inventory/windows/cpu.t

Add CORECOUNT support based on dmidecode output:
- dmidecode 'Core Enabled' is now the default extracted CORE
- Add dmidecode 'Core Count' as CORECOUNT if different than CORE
This patch will permit to show total available cores on physical machine with core disabled by Bios.

2.3.x+dmidecode core count support

---

lib/FusionInventory/Agent/Task/Inventory/Linux/Storages.pm
lib/FusionInventory/Agent/Tools/Linux.pm

Fix & update Storage inventory support for Linux
Tested:
- PCI-based block storages are recognized (SSD disks)
- MMC cards are recognized as removable

2.3.x+linux storage update

---

lib/FusionInventory/Agent/Tools/Hardware.pm

Attempt to fix #252 as only macAddress LldpChassiIdSubtype was really supported

NetInventory: Check LldpChassisIDSubtype

---

lib/FusionInventory/Agent/Task/Inventory.pm
lib/FusionInventory/Agent/Task/Inventory/Generic/Dmidecode/Memory.pm

On virtual systems, memory capacity is often exposed as one component. dmidecode only reports initial capacity in that case. This PR updates the component capacity to the total memory size set in HARDWARE section in such case. So any virtually allocated memory change will be also reported by the agent at the memory component level.
I had to introduce escape conditions support in inventory module dependencies as total memory size is detected in platform dependent modules.

Update memory component capacity on virtual systems

---

lib/FusionInventory/Agent/Task/Inventory/Win32/Softwares.pm

Fix win32 softwares disappear if at least 2 'inventory' are set in tasks

---

lib/FusionInventory/Agent/Tools/Hardware.pm

This was tested with enterasys snmp walk to fixes #336 and generates an inventory which could be included server-side without error even if it was not exact regarding CDP cache info integration. More work will have to be done later on that to identify problematic case.

Better cleanup canonical strings after first invalid character

---

bin/fusioninventory-netdiscovery

I can't figure out how we can have missed that...
This should fix #197 using the right option syntax

Fix credentials option support

---

lib/FusionInventory/Agent/Tools/Hardware.pm
resources/walks/sample4.result
t/agent/tools/hardware.t

Remove VENDOR from netdiscovery/netinventory
Reset MANUFACTURER to well-known real vendor based on detected vendor as model first word
Actually only dell is recognized.

2.3.x+fix hardware manufacturer to real vendor

---

lib/FusionInventory/Agent/Tools.pm
lib/FusionInventory/Agent/Tools/Hardware.pm
lib/FusionInventory/Agent/Tools/Network.pm

This PR makes netinventory more reliable when listing VLANs and so this helps compare results during snmp walks tests.
Canonical string API is also safer and produce utf-8 characters.
Device description is now a canonical string to remove unwanted chars.
Also updated alt2canonical API mac address regexp to be a lot more accurate.

2.3.x+snmp hardware fixes

---

bin/fusioninventory-injector

issue #329 
Catch exceptions. 
If caught exception, print exception message and do exit with non-zero integer.

Fix issue #329 : fusioninventory-injector always returns exit code 0

---

lib/FusionInventory/Agent/SNMP/Device.pm
lib/FusionInventory/Agent/SNMP/MibSupport.pm
lib/FusionInventory/Agent/SNMP/MibSupport/Digi.pm
lib/FusionInventory/Agent/SNMP/MibSupport/iLO.pm
lib/FusionInventory/Agent/SNMP/MibSupportTemplate.pm
lib/FusionInventory/Agent/SNMP/Mock.pm
lib/FusionInventory/Agent/Tools/Hardware.pm
lib/FusionInventory/Agent/Tools/SNMP.pm
resources/walks/sample4.result
t/agent/tools/hardware.t

sysORID OID entries can be used by devices to show which MIB the device supports
This PR adds the sysORID support to activate dedicated module. It can be a better and more reliable EXTMOD replacement as EXTMOD is only activated by sysocject.ids file update. This means any new device can activate the module even if it is not known in sysobject.ids.
The new FusionInventory::Agent::SNMP::Device also introduces the MODEMS/FIRMWARES/SIMCARDS spec support.
As a good example, I added a dedicated Digi module which adds MODEMS and related FIRMWARES infos as Digi devices show it support sarianMonitor MIB.
This PR is also an invitation to refactor SNMP device support around FusionInventory::Agent::SNMP::Device class

2.4.x+netinventory mibsupport detection

---

lib/FusionInventory/Agent/Task/Inventory/Solaris/Drives.pm
lib/FusionInventory/Agent/Tools/Unix.pm
resources/solaris/df/zfs-samples
resources/solaris/mount/zfs-samples
t/tasks/inventory/solaris/drives.t

df command on Solaris reports 0 as total sometime and so Drives module was skipping file systems
This PR fixes the problem and introduces a new unittest.

2.4.x+solaris drives fix

---

Changes
lib/FusionInventory/Agent/Tools.pm

This fix a bug where an inventory can be blocked if a command is waiting forever.
To reproduce, from the source base folder without the patch applied, try the following commandline:
```
time perl -Ilib -e 'use FusionInventory::Agent::Logger; use FusionInventory::Agent::Tools; $logger = FusionInventory::Agent::Logger->new(debug => 2); sub test { print "waiting...\n"; @lines = getAllLines(command => "cat", logger => $logger); print "done\n"; }; runFunction(module => "main", function => "test", timeout => 5, logger => $logger ); print STDERR "DONE\n";'
```
Even if timeout to runFunction is set to 5 seconds, the `cat` command expects input on stdin and blocks the perl script. You can then only stop the process by breaking process input pressing CTRL+C.
After the patch is applied, the command …

Force command to also timeout

---

lib/FusionInventory/Agent/Tools/Hardware.pm

If an XML netinventory printer contains a space in fail to import in glpi
`<CARTRIDGEMAGENTA INK>91</CARTRIDGEMAGENTA INK>`
`  plugins/fusioninventory/front/communication.php:93
PluginFusioninventoryCommunication->handleOCSCommunication()
plugins/fusioninventory/index.php:59               include_once()
2017-12-04 16:19:42 [9@srv-glpi]
*** PHP Warning(2): simplexml_load_string():
&lt;CARTRIDGEMAGENTA INK&gt;91&lt;/CARTRIDGEMAGENTA INK&gt;
Backtrace :
:
...fusioninventory/inc/communication.class.php:433 simplexml_load_string()
plugins/fusioninventory/front/communication.php:93
PluginFusioninventoryCommunication->handleOCSCommunication()
plugins/fusioninventory/index.php:59               include_once()
2017-12-04 16:19:42 [9@srv-glpi]
*** PHP Warning(2): simplexml_load_string():
^
Backtrace …

Remove space for color consumable in XML tag

---

Changes
bin/fusioninventory-netinventory
lib/FusionInventory/Agent/SNMP/Device.pm
lib/FusionInventory/Agent/SNMP/Live.pm
lib/FusionInventory/Agent/SNMP/Mock.pm
lib/FusionInventory/Agent/Task/NetDiscovery.pm
lib/FusionInventory/Agent/Task/NetDiscovery/Version.pm
lib/FusionInventory/Agent/Task/NetInventory.pm
lib/FusionInventory/Agent/Task/NetInventory/Version.pm

This should avoid to reset to a wrong MAC at SNMP detection level.
This should fix cases where device is not imported while MAC doesn't match any more.

Keep first MAC address found while discovering

---

Changes
Makefile.PL
bin/fusioninventory-agent
lib/FusionInventory/Agent/Daemon.pm

Get rid of Proc::PID::File - Fix #424.
Also make filename optional to --pidfile option.
Check against pid file only if --pidfile is used as service manager
like systemd doesn't expect with handle ourself to run or not.
Fix PID file checking even in foreground mode.
Be sure to keep libdir in @INC before daemonize.

Linux daemon updates

---

Changes
lib/FusionInventory/Agent/SNMP/Device.pm
lib/FusionInventory/Agent/SNMP/MibSupport/Epson.pm
lib/FusionInventory/Agent/SNMP/MibSupport/HPNetPeripheral.pm
lib/FusionInventory/Agent/SNMP/MibSupport/Mikrotik.pm
lib/FusionInventory/Agent/SNMP/MibSupportTemplate.pm
lib/FusionInventory/Agent/Task/NetDiscovery/Version.pm
lib/FusionInventory/Agent/Task/NetInventory/Version.pm
lib/FusionInventory/Agent/Tools/Hardware.pm
lib/FusionInventory/Agent/Tools/SNMP.pm

* Added support for HP Net Peripheral, involving better HP printers inventory
- Get Serial number & firmware version
- Fix total printed pages counter in many case
- Added total color pages counter support
* Don't assume colors table was read: fixes black toner detection on many HP printers
* Updated LLDP support to avoid annoying errors

2.4.x+netinventory updates

---

Changes
lib/FusionInventory/Agent/Task/NetInventory.pm
lib/FusionInventory/Agent/Task/NetInventory/Version.pm
t/tasks/netinventory.t

Support DEVICE given PID
Bump NetInventory task version to 3.0
The goal is to enable again the NetInventory task multi-threading support as it's broken since an old server-side protocol change.

NetInventory protocol upgrade

---

Changes
lib/FusionInventory/Agent/Task/NetDiscovery.pm

Add -PE option to nmap to also send ICMP echo requests, so devices not supporting
ICMP timestamp requests can also be discovered.

Update nmap options for NetDiscovery task

---

Changes
lib/FusionInventory/Agent/Task/Inventory/Generic/Dmidecode.pm
lib/FusionInventory/Agent/Task/Inventory/Linux/Bios.pm

`dmidecode` is enabled only if command also reports output, not just if it is found.
This gives minimal Bios & Hardware informations under linux while not running as root.

Support reading Bios & Hardware infos from /sys/class under linux

---

Changes
lib/FusionInventory/Agent/SNMP/Mock.pm

This update permits to divide by 3 the time passed to handle a bunch of big test snmp walks. On my dev station, the run time was more than 12 minutes before for our private snmpwalk repository, and it is now less than 4 minutes.
The update optimize the way OID are stored and accessed. The longer step is still far the file loading and OID indexing time.

Feature: better snmp mock performance

---

Changes
lib/FusionInventory/Agent/SOAP/VMware/Host.pm

fix wrong computation when only one package is available as
totalCore was divided by the reference value, not just 1.

fix cpu core computation
