lib/FusionInventory/Agent.pm
New PR to close fusioninventory/pull/28
=> Fix missed spelled API call

bin/fusioninventory-injector
=> fusioninventory-injector option to read useragent from xml

lib/FusionInventory/Agent/Tools/Hardware.pm
This commit fixes the VLAN/port association for HP switches.
Signed-off-by: Quentin Bouteiller <quentin@quent1.fr>
=> Fix VLAN association

lib/FusionInventory/Agent/Tools/Solaris.pm, t/agent/tools/solaris.t, t/tasks/inventory/solaris/memory.t
This one should do the job taking the number of DIMMs when available or computing the number of DIMMs from DIMM Size and available Logical Size
=> 2.3.x+bugfix 2907 better fix

Changes, bin/fusioninventory-netinventory, lib/FusionInventory/Agent/Task/NetDiscovery.pm, lib/FusionInventory/Agent/Task/NetInventory.pm, t/apps/netdiscovery.t, t/apps/netinventory.t
=> 2.3.x+net tasks multi threading refactoring update

lib/FusionInventory/Agent/Task/Collect.pm, lib/FusionInventory/Agent/Tools/Win32.pm
This update is for 2.3.17 release. It essentially fixes getFromRegistry Collect task.
Sorry unittests are missing ;)
=> 2.3.x+collect task update

lib/FusionInventory/Agent/Inventory.pm, lib/FusionInventory/Agent/Task/Inventory/Virtualization/Virtuozzo.pm, lib/FusionInventory/Agent/Task/Inventory/Virtualization/Vmsystem.pm
Should finally close forge bug 3002
=> Typo: Use right existing hash

lib/FusionInventory/Agent/Tools/Hardware.pm
=> Add Kyocera Specific Counter

Changes, lib/FusionInventory/Agent/HTTP/Server.pm
Trigger an error to help debug deployment not working while Digest::SHA is missing.
=> Trigger error while Digest::SHA is missing as deployment requirement

lib/FusionInventory/Agent/Task/Collect.pm, lib/FusionInventory/Agent/Tools/Win32.pm
Fix Collect task executions to clearly identify when jobs are done
Fix few errors on sometime undefined values
Add _sid job param support as used on recent FusionInventory for GLPI plugin
=> 2.3.x+collect fix

lib/FusionInventory/Agent/Task/Inventory/Win32/Softwares.pm, lib/FusionInventory/Agent/Tools/Win32.pm, t/tasks/inventory/windows/softwares.t
Better Windows apps installation date reporting
=> 2.3.x+win32 installdate fix

Changes, Makefile.PL, README, lib/FusionInventory/Agent/Task/Deploy/File.pm, lib/FusionInventory/Agent/Task/Deploy/P2P.pm, t/01compile.t, t/tasks/deploy/p2p.t
deploy task:
* Backport some master branch work done by guillomovitch on P2P support
* Net::Ping & Parallel::ForkManager library are now mandatory for P2P support
* POE & POE::Component::Client::Ping requirements are now obsolete
* Also add few fixes and enhancement to P2P support
* Added unittest for P2P support
=> P2P support fix & enhancement for deploy task

lib/FusionInventory/Agent/Tools/Network.pm
This fix helps on older windows platform and fix "unable to translate binary address for ..." cases but where you still can resolv dns name on host.
=> Also try legacy dns resolving if IPv6 compatible version fails

lib/FusionInventory/Agent/Task/Deploy/ActionProcessor/Action/Cmd.pm, lib/FusionInventory/Agent/Tools/Win32.pm
These updates essentially helps people to debug command execution failures.
=> 2.3.x+update deploy cmd support

lib/FusionInventory/Agent.pm, t/agent/agent.t
=> correction

bin/fusioninventory-injector
=> Support injector recursive option (close #59)

Changes, bin/fusioninventory-win32-service, lib/FusionInventory/Agent.pm, lib/FusionInventory/Agent/HTTP/Server.pm
=> 2.3.x+upstream win32 service refactoring

lib/FusionInventory/Agent/HTTP/Client/Fusion.pm, t/agent/http/client/fusion/response.t
Fix a case under win32
Add new dedicated unittests including the previously failing case
Also enhance communication error reporting
=> Use safer Pure Perl JSON

bin/fusioninventory-agent
Necessary help for new options. With a few examples.
=> New options 'conf-reload-interval' and 'tasks' command-line help

t/01compile.t
for modules requiring non-mandatory dependencies, if not present
=> additional filtering

lib/FusionInventory/Agent/Inventory.pm, lib/FusionInventory/Agent/Task/Inventory.pm, t/agent/inventory.t
=> 2.3.x+support operatingsystem in additional content

lib/FusionInventory/Agent/Task/Inventory/Virtualization/Xen.pm, resources/virtualization/xm/xl_list, resources/virtualization/xm/xl_list_-v_vmname, t/tasks/inventory/virtualization/xen.t
=> WIP: Add support for Xen >=4.1 xl toolstack

lib/FusionInventory/Agent/Task/Inventory/Virtualization/XenCitrixServer.pm
Special characters in regexp should be escaped.
=> Fix regexp in XenCitrixServer.pm

bin/fusioninventory-win32-service, lib/FusionInventory/Agent.pm
=> wrong key in hash, could not work, now fixed

lib/FusionInventory/Agent/Task/Inventory/MacOS/Softwares.pm, t/tasks/inventory/macos/softwares.t
Wrong format for INSTALLDATE in SOFTWARES part of Inventory for Mac OS X
=> 2.3.x bug INSTALLDATE Mac OS X

lib/FusionInventory/Agent/Inventory.pm, lib/FusionInventory/Agent/Task/Inventory/Generic/Rudder.pm
=> Bug 3047/fix rudder detection

lib/FusionInventory/Agent/Inventory.pm, lib/FusionInventory/Agent/Task/Inventory/Generic/Rudder.pm
Ticket: http://forge.fusioninventory.org/issues/3048
=> Add Rudder agent capapbilites inventory support to the Rudder module

lib/FusionInventory/Agent/Task/Inventory/Virtualization/Lxd.pm
=> 2.3.x+lxd support

Makefile.PL, lib/FusionInventory/Agent/Task/Inventory/MacOS/Softwares.pm, lib/FusionInventory/Agent/Tools/MacOS.pm, t/agent/tools/macos.t, t/tasks/inventory/macos/softwares.t
Use of pure Perl module XML::TreePP with complement module Tie::IxHash to keep XML elements order
=> Mac OS X inventory : SOFTWARES section data retrieving refactoring. 

lib/FusionInventory/Agent/Tools.pm, lib/FusionInventory/Agent/Tools/MacOS.pm, t/tasks/inventory/macos/uptime.t
Mac OS X 10.11 has different output for the command sysctl
=> Mac OS X inventory : boottime

lib/FusionInventory/Agent/Task/Inventory/Win32/Softwares.pm, lib/FusionInventory/Agent/Tools/Win32.pm
In addition of current way to retrieve user software, we introduce a method that search through the registry. 
Actually, the method using the "Ntuser.dat" file in user directory is not sufficient because the Ntuser.dat file is not always present.
=> Win32 : Retrieving user software also from registry

Makefile.PL, README, lib/FusionInventory/Agent/Inventory.pm, lib/FusionInventory/Agent/Task/Inventory/Generic/Timezone.pm
Related to issue https://github.com/fusioninventory/fusioninventory-agent/issues/166
=> Fixes #166: inventory the local timezone name and offset to UTC

Makefile.PL, lib/FusionInventory/Agent/Task/Deploy.pm, t/tasks/deploy/validate.t
Cleanup from unused module in Deploy task and bump version
=> Don't depend on JSON but JSON::PP

lib/FusionInventory/Agent/Config.pm
=> Better config value parsing

lib/FusionInventory/Agent/HTTP/Client/ArmaditoAV.pm, lib/FusionInventory/Agent/HTTP/Client/ArmaditoAV/Event.pm, lib/FusionInventory/Agent/HTTP/Client/ArmaditoAV/Event/StatusEvent.pm, lib/FusionInventory/Agent/Task/Inventory/Linux/AntiVirus.pm, lib/FusionInventory/Agent/Task/Inventory/Linux/AntiVirus/Armadito.pm
Adding Armadito Antivirus RESTful client in HTTP libs
Adding Armadito Antivirus Inventory for Linux
Made in order that tests does not fail if Antivirus is not here.
=> 2.3.x+armaditoav

lib/FusionInventory/Agent/Task/Inventory/Generic/Remote_Mgmt/TeamViewer.pm
=> Support TeamViewer ID inventory for win32

lib/FusionInventory/Agent/Tools/Win32.pm, t/agent/tools/win32.t, t/lib/fake/windows/Win32/TieRegistry.pm
Fix issue where a registry key path contains a least one space
=> 2.3.x+win32 getregistry fix

Changes, bin/fusioninventory-agent, bin/fusioninventory-injector, lib/FusionInventory/Agent.pm, lib/FusionInventory/Agent/Config.pm, lib/FusionInventory/Agent/HTTP/Client.pm, lib/FusionInventory/Agent/HTTP/Client/OCS.pm, lib/FusionInventory/Agent/Task/ESX.pm, lib/FusionInventory/Agent/Task/Inventory.pm, lib/FusionInventory/Agent/Task/NetDiscovery.pm, lib/FusionInventory/Agent/Task/NetInventory.pm
Add no-compression option support
Closes #169
=> 2.3.x+no compression option

lib/FusionInventory/Agent/HTTP/Client/ArmaditoAV.pm, lib/FusionInventory/Agent/Task/Inventory/Linux/AntiVirus/Armadito.pm
This avoid an error message "Can't connect to..." while doing inventory if ArmaditoAV is not present
=> ping ArmaditoAV socket to enable its inventory

lib/FusionInventory/Agent/Task/Inventory/MacOS/Batteries.pm, resources/macos/system_profiler/10.11-system_profiler_SPPowerDataType.txt, t/tasks/inventory/macos/batteries.t
All fields in specification are provided except CHEMISTRY and DATE.
=> Mac OS X Batteries

lib/FusionInventory/Agent/Task/Inventory/Virtualization/VirtualBox.pm
=> removing 10 users limitation

lib/FusionInventory/Agent/Task/Inventory/Generic/Remote_Mgmt/TeamViewer.pm
=> TeamviewerID inventory support for MacOS

lib/FusionInventory/Agent.pm
=> Handle daemon rescheduling on net error

Changes, lib/FusionInventory/Agent/Task/Deploy.pm, lib/FusionInventory/Agent/Task/Deploy/CheckProcessor.pm, lib/FusionInventory/Agent/Task/Deploy/CheckProcessor/DirectoryExists.pm, lib/FusionInventory/Agent/Task/Deploy/CheckProcessor/DirectoryMissing.pm, lib/FusionInventory/Agent/Task/Deploy/CheckProcessor/FileExists.pm, lib/FusionInventory/Agent/Task/Deploy/CheckProcessor/FileMissing.pm, lib/FusionInventory/Agent/Task/Deploy/CheckProcessor/FileSHA512.pm, lib/FusionInventory/Agent/Task/Deploy/CheckProcessor/FileSHA512Mismatch.pm, lib/FusionInventory/Agent/Task/Deploy/CheckProcessor/FileSizeEquals.pm, lib/FusionInventory/Agent/Task/Deploy/CheckProcessor/FileSizeGreater.pm, lib/FusionInventory/Agent/Task/Deploy/CheckProcessor/FileSizeLower.pm, lib/FusionInventory/Agent/Task/Deploy/CheckProcessor/FreeSpaceGreater.pm, lib/FusionInventory/Agent/Task/Deploy/CheckProcessor/WinKeyEquals.pm, lib/FusionInventory/Agent/Task/Deploy/CheckProcessor/WinKeyExists.pm, lib/FusionInventory/Agent/Task/Deploy/CheckProcessor/WinKeyMissing.pm, lib/FusionInventory/Agent/Task/Deploy/Job.pm, lib/FusionInventory/Agent/Task/Deploy/Version.pm, t/tasks/deploy/checkprocessor.t
Deploy task audit enhancement
This fixes #205
=> 2.3.x+deploy audit enhancement

t/tasks/deploy/checkprocessor.t
=> missing mock

CONTRIB.md, README.md
Document contrib folder in sources
Add references to #220 and #256, recent contrib updates proposed as PR, so we can close these PRs without needing to merge them.
Explain how to propose a new contrib reference
=> Add dedicated CONTRIB page in sources

lib/FusionInventory/Agent/Task/Inventory/BSD/Storages.pm, resources/bsd/storages/dmesg, resources/bsd/storages/kern.geom.confxml, t/tasks/inventory/bsd/storages.t
FreeBSD storages retrieving was wrong. 
It was looking at file systems instead of physical devices. 
Now it looks for disks using 'sysctl' command. Then it retrieves more data for each found device using 'dmesg' command.
=> freeBSD storages 

lib/FusionInventory/Agent/Task/Inventory/Linux/ARM/Board.pm, resources/linux/proc/cpuinfo/linux-raspberry-pi-3-model-b, t/tasks/inventory/linux/arm/board.t, t/tasks/inventory/linux/cpu.t
Add ARM Board support
Fix #289
=> 2.3.x+raspberrypi serialnumber

lib/FusionInventory/Agent/Task/Deploy.pm, lib/FusionInventory/Agent/Task/Deploy/ActionProcessor/Action/Cmd.pm
Mainly fix Deploy action command reporting so people can easily debug action processing
Update logLineLimit parameter support
Add support for action name parameter
Server code part will be updated by @wawax for next FI4G release.
=> 2.3.x+deploy cmd output log on server

lib/FusionInventory/Agent/Task/Inventory/Virtualization/Lxc.pm, lib/FusionInventory/Agent/Task/Inventory/Virtualization/Vmsystem.pm, lib/FusionInventory/Agent/Tools/Virtualization.pm
UUID defined as sha1 sum of string containing /etc/machine-id and /etc/hostname contents
=> Support UUID for lxc containers

lib/FusionInventory/Agent/Task/Inventory/MacOS/Storages.pm, lib/FusionInventory/Agent/Tools.pm, t/tasks/inventory/macos/storages.t
Mac Os X storages refacto : use of Tools::getCanonicalSize() ; little modification of this function
=> Mac OS X storages refacto

lib/FusionInventory/Agent.pm, lib/FusionInventory/Agent/HTTP/Server.pm, lib/FusionInventory/Agent/Task/Deploy/ActionProcessor/Action/Copy.pm, lib/FusionInventory/Agent/Task/Deploy/ActionProcessor/Action/Move.pm, lib/FusionInventory/Agent/Task/Deploy/Datastore.pm, lib/FusionInventory/Agent/Task/Deploy/File.pm
Fix perl 5.26 Travis warning ([see warning sample here](https://travis-ci.org/fusioninventory/fusioninventory-agent/jobs/245806718))
=> Fix usage of deprecated api in perl 5.26

lib/FusionInventory/Agent/HTTP/Client.pm
Also debug we may use a proxy to help admins solve communication problems
=> Report proxy error when possible

lib/FusionInventory/Agent/Task/Inventory/AIX.pm
Replace PR #24 following @guillomovitch suggestions
=>  Include TL in AIX OS Version

bin/fusioninventory-agent, bin/fusioninventory-win32-service, contrib/unix/fusioninventory-agent.service, lib/FusionInventory/Agent.pm, lib/FusionInventory/Agent/Daemon.pm, lib/FusionInventory/Agent/Daemon/Win32.pm, lib/FusionInventory/Agent/HTTP/Server.pm, lib/FusionInventory/Agent/Target.pm, lib/FusionInventory/Agent/Tools/Win32.pm, lib/setup.pm, resources/config/daemon1, t/01compile.t, t/agent/daemon.t
Less creative refacto following suggestions made by @guillomovitch as #322 comment
=> 2.3.x+ daemon & service refacto

lib/FusionInventory/Agent/Task/Deploy.pm, lib/FusionInventory/Agent/Task/Deploy/Job.pm, lib/FusionInventory/Agent/Task/Deploy/UserCheck.pm, lib/FusionInventory/Agent/Task/Deploy/UserCheck/WTS.pm, lib/FusionInventory/Agent/Task/Deploy/Version.pm, lib/FusionInventory/Agent/Tools/Win32/WTS.pm, t/01compile.t
This PR introduces user interaction on win32 platform based on WTS APIs for the deployment jobs.
This PR is mandatory to support new server feature added in [User interactions PR](https://github.com/fusioninventory/fusioninventory-for-glpi/pull/2198) by @wawax
=> Deploy task win32 user interaction support

lib/FusionInventory/Agent/Tools/Network.pm, t/agent/tools/network.t
We can find such mac address as snmp string during netinventory
=> Support more alternate mac address format

lib/FusionInventory/Agent/Task/Inventory/Win32/Slots.pm
=> Avoid possible exception on slot not defined win32 current usage

bin/fusioninventory-injector
=> Support XML file extension in injector script

lib/FusionInventory/Agent/Task/Inventory/Virtualization/Xen.pm, resources/virtualization/xm/xl_list2, t/tasks/inventory/virtualization/xen.t
=> github issue #176 : CitrixXen server vm's don't get collected if they have spaces in names.

Changes, Makefile.PL, bin/fusioninventory-inventory, lib/FusionInventory/Agent.pm, lib/FusionInventory/Agent/Config.pm, lib/FusionInventory/Agent/Daemon.pm, lib/FusionInventory/Agent/Task.pm, lib/FusionInventory/Agent/Task/Inventory.pm, lib/setup.pm, t/agent/agent.t, t/agent/daemon.t, t/agent/tools/hardware.t, t/apps/agent.t
Try to get rid of setup.pm confdir definition need
=> 2.4.x+confdir cleanup

bin/fusioninventory-injector
=> Add --no-ssl-check option to injector

lib/FusionInventory/Agent/Task/Inventory/Generic/Dmidecode/Bios.pm, resources/generic/dmidecode/dell-fx160, resources/generic/dmidecode/dell-fx170, t/tasks/inventory/generic/dmidecode/bios.t, t/tasks/inventory/generic/dmidecode/memory.t
This should fix the following forum reported issue for a Dell computer:
[Remontée Service Tag Dell sur client léger Win XP/7](http://forum.fusioninventory.org/viewtopic.php?pid=24351#p24351)
=> Serial Number can be in chassis information

lib/FusionInventory/Agent/Tools/Solaris.pm, t/agent/tools/solaris.t, t/tasks/inventory/solaris/memory.t
=> Fix Solaris memory components type

lib/FusionInventory/Agent/Task/NetDiscovery.pm, lib/FusionInventory/Agent/Task/NetInventory.pm
It seems to happen a task remains blocked until service is restarted. Handling an expiration in main thread may help or if this continue to fails sometime we will need to better use Parallel::ForkManager module.
=> Add Expiration time support in NetDiscovery & Netinventory

Changes, lib/FusionInventory/Agent/Task/Inventory/Win32/AntiVirus.pm
- Get antivirus version from software installation (Fix #364)
- Get Windows Defender version via WMI
=> Windows antivirus support update

lib/FusionInventory/Agent/Task/Inventory/Win32/Networks.pm, lib/FusionInventory/Agent/Tools/Win32.pm, t/tasks/inventory/windows/networks.t
* Fix network mediatype support
* Avoid to call getRegistryKey API as time as found network interface
=> Fix network mediatype support

bin/fusioninventory-agent, bin/fusioninventory-wmi, lib/FusionInventory/Agent/Daemon/Win32.pm, lib/FusionInventory/Agent/Task/Inventory.pm, lib/FusionInventory/Agent/Task/WMI.pm, lib/FusionInventory/Agent/Tools/Win32.pm
Few more enhancements and fixes for WMI task support
As a side effect, logger is now working in the Win32::OLE worker thread, even for normal inventory.
=> 2.4.x+wmi task updates

Changes, lib/FusionInventory/Agent/SNMP/Device.pm, lib/FusionInventory/Agent/Tools/Hardware.pm, lib/FusionInventory/Agent/Tools/SNMP.pm
Regression fix: RAM & CPU are missing from net inventory
=> 2.4.x+netinventory mem cpu fix

Changes, lib/FusionInventory/Agent/Task/NetDiscovery.pm, resources/nmap/10.0.1.128, resources/nmap/11.52.5.241, t/tasks/network/nmap.t
Discover devices even if they only respond to ping and dns doen't report a hostname.
=> 2.4.x+fix discovery missed devices

Changes, bin/fusioninventory-agent, bin/fusioninventory-wmi, lib/FusionInventory/Agent.pm, lib/FusionInventory/Agent/Daemon.pm, lib/FusionInventory/Agent/HTTP/Server.pm, lib/FusionInventory/Agent/Target.pm, lib/FusionInventory/Agent/Target/Local.pm, lib/FusionInventory/Agent/Target/Server.pm, lib/FusionInventory/Agent/Task/Collect.pm, lib/FusionInventory/Agent/Task/Deploy.pm, lib/FusionInventory/Agent/Task/ESX.pm, lib/FusionInventory/Agent/Task/Inventory.pm, lib/FusionInventory/Agent/Task/NetDiscovery.pm, lib/FusionInventory/Agent/Task/NetInventory.pm, lib/FusionInventory/Agent/Task/WMI.pm, lib/FusionInventory/Agent/Task/WakeOnLan.pm
* Normalized few Target class API
* Register planned task by Target
=> Target class API refacto

lib/FusionInventory/Agent/Tools/Hardware/Brocade.pm, lib/FusionInventory/Agent/Tools/Hardware/Qlogic.pm
=> Update extmod function calls

Changes, lib/FusionInventory/Agent/SNMP/Device.pm, lib/FusionInventory/Agent/SNMP/MibSupport/LinuxAppliance.pm, lib/FusionInventory/Agent/SNMP/MibSupportTemplate.pm, lib/FusionInventory/Agent/Tools/Hardware.pm
Add Linux Appliance template support
=> Add QuesCom Appliance detection

Changes, lib/FusionInventory/Agent/Task/Inventory/Generic/Batteries/Acpiconf.pm, resources/generic/batteries/acpiconf/dmidecode_1.txt, resources/generic/batteries/acpiconf/infos_1.txt, t/tasks/inventory/generic/batteries/acpiconf.t
Test with samples given by @ddurieux in #240
=> Add BSD batteries support

Changes, lib/FusionInventory/Agent/Task/Inventory/MacOS/Videos.pm, resources/macos/system_profiler/asus-geforce-gt-730, t/tasks/inventory/macos/videos.t
=> Set monitor serial number on MacOS

lib/FusionInventory/Agent/Task/Inventory/Generic/Batteries/Acpiconf.pm, lib/FusionInventory/Agent/Task/Inventory/Generic/Batteries/Upower.pm, lib/FusionInventory/Agent/Task/Inventory/Generic/Dmidecode/Battery.pm, lib/FusionInventory/Agent/Tools/Batteries.pm, t/tasks/inventory/generic/batteries/acpiconf.t, t/tasks/inventory/generic/dmidecode/battery.t
Fix suggested by @ddurieux  in #515 
In Acpiconf, I also changed 'Last full capacity' usage to 'Design capacity'.
This makes me think in some case we would be able to calculate current real capacity. This may be interesting to show some batteries should be replaced.
=> Fix batteries capacity & voltage values support

lib/FusionInventory/Agent/Task/Inventory/Virtualization/Qemu.pm, t/tasks/inventory/virtualization/qemu.t
=> Fix kvm commandline parsing

Changes, lib/FusionInventory/Agent/Tools/Hardware.pm
=> Skip cdp/edp support if ip is not defined

Changes, lib/FusionInventory/Agent/Task/Inventory/Win32/Softwares.pm, lib/FusionInventory/Agent/Tools/Win32/API.pm, lib/FusionInventory/Agent/Tools/Win32/LoadIndirectString.pm, lib/FusionInventory/Agent/Tools/Win32/WideChar.pm
Add UWP/APPX/Windows Store software inventory
Add API to convert multibytes string to and from widechar strings
Add API to load indirect strings
Closes #299
=> Add UWP/APPX/Windows Store software inventory

Changes, lib/FusionInventory/Agent/SOAP/VMware/Host.pm, t/agent/soap.t
Support 2 ServiceTags case to cover chassis & lame board S/N inventory
Updated AssetTag support
=> feature(esx): servicetag & assettag support update

Changes, lib/FusionInventory/Agent/Task/Deploy/Job.pm
This new feature requires a plugin update.
=> permit to skip remaining audit check for a deploy job
